using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;

namespace LELEngine.Editor
{
	/// <summary>
	///     Writes the C# project of a game project, so the scripts can be edited (and debugged, by attaching to the
	///     editor) in any IDE: &lt;Name&gt;.csproj compiling Assets/**/*.cs into Game.dll against the editor's engine
	///     assemblies, &lt;Name&gt;.sln, and Directory.Build.props moving obj/ into Library/. The files are regenerated
	///     when they change (e.g. the editor moved); NuGet packages go into &lt;Name&gt;.packages.props, which is never
	///     overwritten.
	/// </summary>
	internal static class ProjectGenerator
	{
		#region PublicFields

		public const string AssemblyName = "Game";

		#endregion

		#region PublicMethods

		public static string ProjectName(ProjectInfo project)
		{
			var builder = new StringBuilder();
			foreach (char c in project.Name)
			{
				if (char.IsLetterOrDigit(c) || c == '_' || c == '.')
				{
					builder.Append(c);
				}
			}

			return builder.Length > 0 ? builder.ToString() : "Game";
		}

		public static string ProjectFile(ProjectInfo project)
		{
			return Path.Combine(project.RootPath, ProjectName(project) + ".csproj");
		}

		public static string SolutionFile(ProjectInfo project)
		{
			return Path.Combine(project.RootPath, ProjectName(project) + ".sln");
		}

		public static void Generate(ProjectInfo project)
		{
			string name = ProjectName(project);
			WriteIfChanged(ProjectFile(project), Csproj(name));
			WriteIfChanged(SolutionFile(project), Sln(name));
			WriteIfChanged(Path.Combine(project.RootPath, "Directory.Build.props"), BuildProps());

			string packages = Path.Combine(project.RootPath, name + ".packages.props");
			if (!File.Exists(packages))
			{
				File.WriteAllText(packages,
					"<Project>\n  <!-- NuGet packages of the game scripts. Example:\n" +
					"  <ItemGroup>\n    <PackageReference Include=\"Some.Package\" Version=\"1.2.3\" />\n  </ItemGroup>\n" +
					"  This file is yours: the editor never overwrites it. -->\n</Project>\n");
			}
		}

		#endregion

		#region PrivateMethods

		private static string Csproj(string name)
		{
			string editor = AppContext.BaseDirectory;
			var references = new List<string> { "LELEngine.dll", "LELCS.dll" };
			references.AddRange(Directory.GetFiles(editor, "OpenTK*.dll").Select(Path.GetFileName).OrderBy(f => f, StringComparer.OrdinalIgnoreCase));

			var builder = new StringBuilder();
			builder.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
			builder.AppendLine();
			builder.AppendLine("  <!-- Generated by the LELEngine editor; it is rewritten when the editor needs other settings.");
			builder.AppendLine("       Add NuGet packages in " + name + ".packages.props. -->");
			builder.AppendLine();
			builder.AppendLine("  <PropertyGroup>");
			builder.AppendLine("    <TargetFramework>net10.0</TargetFramework>");
			builder.AppendLine("    <AssemblyName>" + AssemblyName + "</AssemblyName>");
			builder.AppendLine("    <RootNamespace>" + Escape(name) + "</RootNamespace>");
			builder.AppendLine("    <Nullable>disable</Nullable>");
			builder.AppendLine("    <ImplicitUsings>disable</ImplicitUsings>");
			builder.AppendLine("    <LangVersion>latest</LangVersion>");
			builder.AppendLine("    <EnableDefaultItems>false</EnableDefaultItems>");
			builder.AppendLine("    <OutputPath>Library\\ScriptAssemblies\\</OutputPath>");
			builder.AppendLine("    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>");
			builder.AppendLine("    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>");
			builder.AppendLine("    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>");
			builder.AppendLine("    <GenerateDependencyFile>false</GenerateDependencyFile>");
			builder.AppendLine("    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>");
			builder.AppendLine("    <DebugType>portable</DebugType>");
			builder.AppendLine("  </PropertyGroup>");
			builder.AppendLine();
			builder.AppendLine("  <ItemGroup>");
			builder.AppendLine("    <Compile Include=\"Assets\\**\\*.cs\" />");
			builder.AppendLine("  </ItemGroup>");
			builder.AppendLine();
			builder.AppendLine("  <!-- Engine assemblies of the editor (not copied: the editor and the player provide them). -->");
			builder.AppendLine("  <ItemGroup>");
			foreach (string reference in references)
			{
				builder.AppendLine("    <Reference Include=\"" + Escape(Path.GetFileNameWithoutExtension(reference)) + "\">");
				builder.AppendLine("      <HintPath>" + Escape(Path.Combine(editor, reference)) + "</HintPath>");
				builder.AppendLine("      <Private>false</Private>");
				builder.AppendLine("    </Reference>");
			}

			builder.AppendLine("  </ItemGroup>");
			builder.AppendLine();
			builder.AppendLine("  <Import Project=\"" + Escape(name) + ".packages.props\" Condition=\"Exists('" + Escape(name) + ".packages.props')\" />");
			builder.AppendLine();
			builder.AppendLine("</Project>");
			return builder.ToString();
		}

		private static string BuildProps()
		{
			return "<Project>\n  <!-- Generated by the LELEngine editor: intermediate files go to Library/. -->\n" +
				"  <PropertyGroup>\n" +
				"    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)Library\\obj\\</BaseIntermediateOutputPath>\n" +
				"    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>\n" +
				"  </PropertyGroup>\n</Project>\n";
		}

		private static string Sln(string name)
		{
			string projectGuid = StableGuid(name).ToString("B").ToUpperInvariant();
			const string csharp = "{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}";
			return "\nMicrosoft Visual Studio Solution File, Format Version 12.00\n# Visual Studio Version 17\n" +
				"Project(\"" + csharp + "\") = \"" + name + "\", \"" + name + ".csproj\", \"" + projectGuid + "\"\nEndProject\n" +
				"Global\n\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n\t\tDebug|Any CPU = Debug|Any CPU\n\t\tRelease|Any CPU = Release|Any CPU\n\tEndGlobalSection\n" +
				"\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n" +
				"\t\t" + projectGuid + ".Debug|Any CPU.ActiveCfg = Debug|Any CPU\n\t\t" + projectGuid + ".Debug|Any CPU.Build.0 = Debug|Any CPU\n" +
				"\t\t" + projectGuid + ".Release|Any CPU.ActiveCfg = Release|Any CPU\n\t\t" + projectGuid + ".Release|Any CPU.Build.0 = Release|Any CPU\n" +
				"\tEndGlobalSection\nEndGlobal\n";
		}

		private static Guid StableGuid(string text)
		{
			using (var md5 = System.Security.Cryptography.MD5.Create())
			{
				return new Guid(md5.ComputeHash(Encoding.UTF8.GetBytes("LELEngine:" + text)));
			}
		}

		private static void WriteIfChanged(string path, string content)
		{
			if (File.Exists(path) && File.ReadAllText(path) == content)
			{
				return;
			}

			File.WriteAllText(path, content);
		}

		private static string Escape(string text)
		{
			return SecurityElement.Escape(text);
		}

		#endregion
	}
}
